# -*- coding: utf-8 -*-
"""전자담배 성분.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvjMCj5d_lFB4X5EhzJwQDBerzgOKZNF

https://www.yna.co.kr/view/AKR20170410169300017
"""

import sys

!sudo add-apt-repository ppa:saiarcot895/chromium-beta
!sudo apt remove chromium-browser
!sudo snap remove chromium
!sudo apt install chromium-browser
!pip3 install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome(options=options)

import pandas as pd

url= 'https://www.yna.co.kr/view/AKR20170410169300017'
driver.get(url)

contents= driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody')

ecTitles= ['구분', '성분명', '(액상 중)- 함량(μg/g)', '(기체상 중)- 함량(μg/g)', '(기체상 중)- 함량(μg/cig*)']
contents= contents.text
contents = contents.splitlines()
n= len(contents)

elements = [[None, None, None, None, None] for _ in range(n-3)]

# 구분, 성분명
for i in range(3, n):
  a=driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody/tr[' + str(i) + ']/td[1]')

  if a.get_attribute('colspan'):
    elements[i-3][0],elements[i-3][1]= a.text, a.text
  elif a.get_attribute('rowspan'):
    rowValue= int(a.get_attribute('rowspan'))
    elements[i-3][1]= driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody/tr[' + str(i) + ']/td[2]').text
    for j in range(rowValue):
      elements[i-3+j][0]= a.text
    cnt= 0
  else:
    if cnt == rowValue:
      continue
    cnt+=1
    elements[i-3][1]=a.text


# (액상 중)- 함량(μg/g), (기체상 중)- 함량(μg/g), (기체상 중)- 함량(μg/cig*)
for i in range(3, n):
  elements[i-3][2]=driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody/tr[' + str(i) + ']/td[last()-2]').text
  elements[i-3][3]=driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody/tr[' + str(i) + ']/td[last()-1]').text
  elements[i-3][4]=driver.find_element('xpath', '//*[@id="articleWrap"]/div[2]/div/div/article/table/tbody/tr[' + str(i) + ']/td[last()]').text


ecDf= pd.DataFrame(elements, columns= ecTitles)
ecDf